active.directory.user=apiLoginUser
active.directory.password=8fsTRNy5X
active.directory.url.azure=http://10.3.0.8:8085/ApiLogin/user/azure/validate
active.directory.app.id=f46383de-97ee-4e09-abe1-d57fc7f0e105

web2lab.autorizacion.permiso=AUTORIZA

mail.send.fromemailmarketing=Info_olab@tjoriard.com.mx
mail.send.copyemailmarketing=infodiamex@olab.com.mx
mail.send.frompasswordmarketing=b9l88f

mail.send.fromemail=servicios.enlinea@grupodiagnosticoaries.com.mx
mail.send.fromemailUser=servicios.enlinea@olab.com.mx 
mail.send.frompassword=PBJ4t-0j0DG
#mail.send.frompassword=f5Y6otz
#mail.send.frompassword=xwP5Qu9EUFbV

mail.send.fromemailece=servicios.enlinea@olab.com.mx 
mail.send.copyfromemailece=infodiamex@olab.com.mx
#mail.send.frompasswordece=f5Y6otz
mail.send.frompasswordece=PBJ4t-0j0DG

#mail.send.fromemail=facturacion.electronica@olab.com.mx
#mail.send.frompassword=t3mp8r9l
#mail.send.frompassword=xwP5Qu9EUFbV


#1n8rtc
mail.send.copyemail=nocopiar

mail.send.smtphost=smtp.sendgrid.net
#mail.send.smtphost=webmail.olab.com.mx
#mail.send.smtphost=207.97.245.100
#mail.send.smtphost=smtp.spacemail.mx
mail.send.smtpport=587

#Configuracion de generacionde archivos en stream 
#o archivo en el servidor
reporte.genera.stream=1
reporte.genera.orden.stream=0
configuracion.listaprecio.mayoreo=3
configuracion.listaprecio.vigente=6


#Configuracion DF
#reporte.ruta.filemarketingread=C:/PromocionMarketing/
#reporte.ruta.pdfwrite=C:/Program Files/Apache Software Foundation/Apache2.2/htdocs/FacturasElectronicas/
#reporte.ruta.pdflocalread=C:/Program Files/Apache Software Foundation/Apache2.2/htdocs/FacturasElectronicas/
##reporte.ruta.pdfwrite=C:/Program Files/Apache Software Foundation/Apache2.2/htdocs/FacturasElectronicas/
##reporte.ruta.pdflocalread=C:/Program Files/Apache Software Foundation/Apache2.2/htdocs/FacturasElectronicas/
#reporte.ruta.xmllocalread=C:/FacturasElectronicasXML/
#reporte.ruta.pdfreadURL=http://localhost/FacturasElectronicas/
#reporte.ruta.imagenes=http://localhost/Imagenes/
#reporte.ruta.sellosread=C:/sellosfacturaelectronica/
#reporte.ruta.jasperread=C:/ReportesJasper/
#reporte.ruta.jasperpdfwrite=C:/Program Files/Apache Software Foundation/Apache2.2/htdocs/Ordenes/
##reporte.ruta.jasperpdfwrite=C:/Program Files/Apache Software Foundation/Apache2.2/htdocs/Ordenes/
#reporte.ruta.jasperpdfread=http://localhost/Ordenes/
#reporte.ruta.excelwrite=C:/ReportesJasper/
#reporte.formatoSSPuebla.guardar=C:/Program Files/Apache Software Foundation/Apache2.2/htdocs/Puebla/
##reporte.formatoSSPuebla.guardar=C:/Program Files/Apache Software Foundation/Apache2.2/htdocs/Puebla/
#reporte.formatoSSPuebla.leer=http://localhost/Puebla/



#Configuracion Desarrollo
#reporte.ruta.filemarketingread=C:/PromocionMarketing/
#reporte.ruta.pdfwrite=C:/Program Files (x86)/Apache Software Foundation/Apache2.2/htdocs/FacturasElectronicas/
#reporte.ruta.pdflocalread=C:/Program Files (x86)/Apache Software Foundation/Apache2.2/htdocs/FacturasElectronicas/
#reporte.ruta.xmllocalread=C:/FacturasElectronicasXML/
#reporte.ruta.pdfreadURL=http://localhost/FacturasElectronicas/
#reporte.ruta.imagenes=http://localhost/Imagenes/
#reporte.ruta.sellosread=C:/sellosfacturaelectronica/
#reporte.ruta.jasperread=C:/ReportesJasper/
#reporte.ruta.jasperpdfwrite=C:/Program Files (x86)/Apache Software Foundation/Apache2.2/htdocs/Ordenes/
#reporte.ruta.jasperpdfread=http://localhost/Ordenes/
#reporte.ruta.excelwrite=C:/ReportesJasper/
#reporte.formatoSSPuebla.guardar=C:/Program Files (x86)/Apache Software Foundation/Apache2.2/htdocs/Puebla/
#reporte.formatoSSPuebla.leer=http://localhost/Puebla/

#Configuracion Produccion Windows
#reporte.ruta.pdfwrite=C:/inetpub/wwwroot/InfoDiaMexProduccion/FacturasElectronicas/
#reporte.ruta.pdflocalread=C:/inetpub/wwwroot/InfoDiaMexProduccion/FacturasElectronicas/
#reporte.ruta.xmllocalread=C:/InfoDiaMexProduccion/FacturasElectronicasXML/
#reporte.ruta.filemarketingread=C:/InfoDiaMexProduccion/PromocionMarketing/
#reporte.ruta.pdfreadURL=http://201.150.42.46:8080/InfoDiaMexProduccion/FacturasElectronicas/
#reporte.ruta.imagenes=C:/inetpub/wwwroot/InfoDiaMexProduccion/Imagenes/
#reporte.ruta.sellosread=C:/InfoDiaMexProduccion/sellosfacturaelectronica/
#reporte.ruta.jasperread=C:/InfoDiaMexProduccion/ReportesJasper/
#reporte.ruta.jasperpdfwrite=C:/inetpub/wwwroot/InfoDiaMexProduccion/Ordenes/
#reporte.ruta.jasperpdfread=http://201.150.42.46:8080/InfoDiaMexProduccion/Ordenes/
#reporte.formatoSSPuebla.guardar=C:/inetpub/wwwroot/InfoDiaMexProduccion/Puebla/
#reporte.formatoSSPuebla.leer=http://201.150.42.46:8080/InfoDiaMexProduccion/Puebla/

#Configuracion Produccion Linux
reporte.ruta.pdfwrite_Olab=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Olab/PDF/
reporte.ruta.pdflocalread_Olab=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Olab/PDF/

reporte.ruta.pdfreadURL_OLab=http://10.3.0.8:9085/FacturasElectronicas_Olab/XMLTMP/PDF/

#reporte.ruta.pdfreadURL_OLab=http://173.203.12.184:9085//FacturasElectronicas_Olab/PDF/
reporte.ruta.xmllocalread_Olab=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Olab/XML/
reporte.ruta.xmlcfdlocalread_Olab=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Olab/CFDXML/
reporte.ruta.imagenesqr_Olab=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Olab/QR/


reporte.ruta.pdfwrite_Azteca=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Azteca/PDF/
reporte.ruta.pdflocalread_Azteca=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Azteca/PDF/

reporte.ruta.pdfreadURL_Azteca=http://10.3.0.8:9085/FacturasElectronicas_Azteca/XMLTMP/PDF/

#reporte.ruta.pdfreadURL_Azteca=http://173.203.12.184:9085//FacturasElectronicas_Azteca/PDF/
reporte.ruta.xmllocalread_Azteca=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Azteca/XML/
reporte.ruta.xmlcfdlocalread_Azteca=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Azteca/CFDXML/
reporte.ruta.imagenesqr_Azteca=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Azteca/QR/


reporte.ruta.pdfwrite_Swisslab=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Swisslab/PDF/
reporte.ruta.pdflocalread_Swisslab=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Swisslab/PDF/

reporte.ruta.pdfreadURL_Swisslab=http://10.3.0.8:9085/FacturasElectronicas_Swisslab/XMLTMP/PDF/

reporte.ruta.xmllocalread_Swisslab=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Swisslab/XML/
reporte.ruta.xmlcfdlocalread_Swisslab=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Swisslab/CFDXML/
reporte.ruta.imagenesqr_Swisslab=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Swisslab/QR/


reporte.ruta.pdfwrite_FamilyLabs=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_FamilyLabs/PDF/
reporte.ruta.pdflocalread_FamilyLabs=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_FamilyLabs/PDF/

reporte.ruta.pdfreadURL_FamilyLabs=http://10.3.0.8:9085/FacturasElectronicas_FamilyLabs/XMLTMP/PDF/

reporte.ruta.xmllocalread_FamilyLabs=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_FamilyLabs/XML/
reporte.ruta.xmlcfdlocalread_FamilyLabs=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_FamilyLabs/CFDXML/
reporte.ruta.imagenesqr_FamilyLabs=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_FamilyLabs/QR/


reporte.ruta.pdfwrite_Exakta=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Exakta/PDF/
reporte.ruta.pdflocalread_Exakta=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Exakta/PDF/

reporte.ruta.pdfreadURL_Exakta=http://10.3.0.8:9085/FacturasElectronicas_Exakta/XMLTMP/PDF/

reporte.ruta.xmllocalread_Exakta=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Exakta/XML/
reporte.ruta.xmlcfdlocalread_Exakta=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Exakta/CFDXML/
reporte.ruta.imagenesqr_Exakta=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Exakta/QR/


reporte.ruta.pdfwrite_JennerPrado=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Jenner/Prado/PDF/
reporte.ruta.pdflocalread_JennerPrado=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Jenner/Prado/PDF/

reporte.ruta.pdfreadURL_JennerPrado=http://10.3.0.8:9085/FacturasElectronicas_Jenner/Prado/XMLTMP/PDF/

#reporte.ruta.pdfreadURL_Azteca=http://173.203.12.184:9085//FacturasElectronicas_Azteca/PDF/
reporte.ruta.xmllocalread_JennerPrado=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Jenner/Prado/XML/
reporte.ruta.xmlcfdlocalread_JennerPrado=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Jenner/CFDXML/
reporte.ruta.imagenesqr_JennerPrado=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Jenner/Prado/QR/

reporte.ruta.pdfwrite_JennerLean=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Jenner/Lean/PDF/
reporte.ruta.pdflocalread_JennerLean=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Jenner/Lean/PDF/

reporte.ruta.pdfreadURL_JennerLean=http://10.3.0.8:9085/FacturasElectronicas_Jenner/Lean/XMLTMP/PDF/

#reporte.ruta.pdfreadURL_Azteca=http://173.203.12.184:9085//FacturasElectronicas_Azteca/PDF/
reporte.ruta.xmllocalread_JennerLean=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Jenner/Lean/XML/
reporte.ruta.xmlcfdlocalread_JennerLean=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Jenner/CFDXML/
reporte.ruta.imagenesqr_JennerLean=/mnt/gda/apache-tomcat/webapps/ROOT/FacturasElectronicas_Jenner/Lean/QR/

#PRUEBAS LOCALES
#reporte.ruta.pdfwrite_Olab=C:/PruebaTimbrado/FacturasElectronicas_Olab/PDF/
#reporte.ruta.pdflocalread_Olab=C:/PruebaTimbrado/FacturasElectronicas_Olab/PDF/

#reporte.ruta.pdfreadURL_OLab=http://10.3.0.8:9085//FacturasElectronicas_Olab/PDF/

#reporte.ruta.xmllocalread_Olab=C:/PruebaTimbrado/FacturasElectronicas_Olab/XML/
#reporte.ruta.xmlcfdlocalread_Olab=C:/PruebaTimbrado/FacturasElectronicas_Olab/CFDXML/
#reporte.ruta.imagenesqr_Olab=C:/PruebaTimbrado/FacturasElectronicas_Olab/QR/


#reporte.ruta.pdfwrite_Azteca=C:/PruebaTimbrado/FacturasElectronicas_Azteca/PDF/
#reporte.ruta.pdflocalread_Azteca=C:/PruebaTimbrado/FacturasElectronicas_Azteca/PDF/

#reporte.ruta.pdfreadURL_Azteca=http://10.3.0.8:9085//FacturasElectronicas_Azteca/PDF/

#reporte.ruta.xmllocalread_Azteca=C:/PruebaTimbrado/FacturasElectronicas_Azteca/XML/
#reporte.ruta.xmlcfdlocalread_Azteca=C:/PruebaTimbrado/FacturasElectronicas_Azteca/CFDXML/
#reporte.ruta.imagenesqr_Azteca=C:/PruebaTimbrado/FacturasElectronicas_Azteca/QR/


#reporte.ruta.pdfwrite_Swisslab=C:/PruebaTimbrado/FacturasElectronicas_Swisslab/PDF/
#reporte.ruta.pdflocalread_Swisslab=C:/PruebaTimbrado/FacturasElectronicas_Swisslab/PDF/

#reporte.ruta.pdfreadURL_Swisslab=http://10.3.0.8:9085//FacturasElectronicas_Swisslab/PDF/

#reporte.ruta.xmllocalread_Swisslab=C:/PruebaTimbrado/FacturasElectronicas_Swisslab/XML/
#reporte.ruta.xmlcfdlocalread_Swisslab=C:/PruebaTimbrado/FacturasElectronicas_Swisslab/CFDXML/
#reporte.ruta.imagenesqr_Swisslab=C:/PruebaTimbrado/FacturasElectronicas_Swisslab/QR/


reporte.ruta.filemarketingread=/mnt/gda/PromocionMarketing/

reporte.ruta.pdfreadURL=http://10.3.0.8:9085/FacturasElectronicas_Olab/PDF/
reporte.ruta.pdfreadURLXML=http://10.3.0.8:9085/FacturasElectronicas_Olab/XML/


#reporte.ruta.pdfreadURL=http://173.203.12.184:9085/FacturasElectronicas_Olab/PDF/
#reporte.ruta.pdfreadURLXML=http://173.203.12.184:9085/FacturasElectronicas_Olab/XML/


reporte.ruta.sellosread=/mnt/gda/OLAB/sellosfacturaelectronica/
reporte.ruta.jasperread=/mnt/gda/OLAB/ReportesJasper/
reporte.ruta.jasperpdfwrite=/mnt/gda/apache-tomcat/webapps/ROOT/Ordenes/
reporte.ruta.imagenes=/mnt/gda/apache-tomcat/webapps/ROOT/Imagenes/
#Produccion 186
#reporte.ruta.jasperpdfread=http://173.203.12.184:9085/Ordenes/
#Produccion 184
#reporte.ruta.jasperpdfread=http://173.203.12.184:9085/Ordenes/

reporte.ruta.jasperpdfread=http://10.3.0.8:9085/Ordenes/

#reporte.ruta.jasperpdfread=http://173.203.12.184:9085/Ordenes/
#InBody
reporte.ruta.resultadoinbodywrite=/mnt/gda/apache-tomcat/webapps/ROOT/InBody/

reporte.ruta.resultadoinbodyread=http://10.3.0.8:9085/InBody/

#reporte.ruta.resultadoinbodyread=http://173.203.12.184:9085/InBody/
#Toxicologia
reporte.ruta.resultadotoxiwrite=/mnt/gda/apache-tomcat/webapps/ROOT/Toxi/

reporte.ruta.resultadotoxiread=http://10.3.0.8:9085/Toxi/

#reporte.ruta.resultadotoxiread=http://173.203.12.184:9085/Toxi/
#Electro
reporte.ruta.resultadoelectrowrite=/mnt/gda/apache-tomcat/webapps/ROOT/Gabinete/Electro/

reporte.ruta.resultadoelectroread=http://10.3.0.8:9085/Gabinete/Electro/

#reporte.ruta.resultadoelectroread=http://173.203.12.184:9085/Gabinete/Electro/
#Lumbar
reporte.ruta.resultadolumbarwrite=/mnt/gda/apache-tomcat/webapps/ROOT/Gabinete/Lumbar/

reporte.ruta.resultadolumbarread=http://10.3.0.8:9085/Gabinete/Lumbar/

#reporte.ruta.resultadolumbarread=http://173.203.12.184:9085/Gabinete/Lumbar/

#Torax
reporte.ruta.resultadotoraxwrite=/mnt/gda/apache-tomcat/webapps/ROOT/Gabinete/Torax/

reporte.ruta.resultadotoraxread=http://10.3.0.8:9085/Gabinete/Torax/

#reporte.ruta.resultadotoraxread=http://173.203.12.184:9085/Gabinete/Torax/

#Conclusiones
reporte.ruta.resultadoconclusioneswrite=/mnt/gda/apache-tomcat/webapps/ROOT/Conclusiones/

reporte.ruta.resultadoconclusionesread=http://10.3.0.8:9085/Conclusiones/

#reporte.ruta.resultadoconclusionesread=http://173.203.12.184:9085/Conclusiones/
#Puebla
reporte.formatoSSPuebla.guardar=/mnt/gda/apache-tomcat/webapps/ROOT/Puebla/

reporte.formatoSSPuebla.leer=http://10.3.0.8:9085/Puebla/

#reporte.formatoSSPuebla.leer=http://173.203.12.184:9085/Puebla/



alta.convenios.users.105820=1,4,5,7,15
#alta.convenios.users.104341=1,4,5,7,15
alta.convenios.users.104341=1,4,5,7,15,17,19,20
alta.convenios.users.105098=1,4,5,7,15
alta.convenios.users.100459=1,4,5,7,15
alta.convenios.users.102313=1,4,5,7,15
alta.convenios.users.105632=1,4,5,7,15
alta.convenios.users.105633=1,4,5,7,15
alta.convenios.users.105634=1,4,5,7,15
alta.convenios.users.106198=1,4,5,7,15
alta.convenios.users.102600=1,4,5,7,15
alta.convenios.users.106329=1,4,5,7,15
alta.convenios.users.106326=1,4,5,7,15
alta.convenios.users.104166=1,4,5,7,15
alta.convenios.users.104167=1,4,5,7,15
alta.convenios.users.104933=1,4,5,7,15
alta.convenios.users.103071=1,4,5,7,15
alta.convenios.users.102099=1,4,5,7,15
alta.convenios.users.103583=1,4,5,7,15
alta.convenios.users.100679=1,4,5,7,15,19,20
alta.convenios.users.104190=1,4,5,7,15
alta.convenios.users.104174=1,4,5,7,15
alta.convenios.users.104191=1,4,5,7,15
alta.convenios.users.105925=1,4,5,7,15
alta.convenios.users.105927=1,4,5,7,15
alta.convenios.users.107240=1,4,5,7,15
alta.convenios.users.105024=1,4,5,7,15
alta.convenios.users.105025=1,4,5,7,15
alta.convenios.users.105009=1,4,5,7,15
alta.convenios.users.102240=1,4,5,7,15
alta.convenios.users.105179=1,4,5,7,15
alta.convenios.users.105178=1,4,5,7,15
alta.convenios.users.108707=1,4,5,7,15
alta.convenios.users.102580=1,4,5,7,15
alta.convenios.users.105010=1,4,5,7,15
alta.convenios.users.102475=1,4,5,7,15
alta.convenios.users.100982=1,4,5,7,15
alta.convenios.users.104613=1,4,5,7,15
alta.convenios.users.105129=1,4,5,7,15
alta.convenios.users.104614=1,4,5,7,15
alta.convenios.users.3229=1,4,5,7,15
alta.convenios.users.105483=1,4,5,7,15
alta.convenios.users.106471=1,4,5,7,15
alta.convenios.users.104664=1,4,5,7,15
alta.convenios.users.102310=1,4,5,7,15
alta.convenios.users.106066=1,4,5,7,15
alta.convenios.users.104370=1,4,5,7,15
alta.convenios.users.105014=1,4,5,7,15
alta.convenios.users.100959=1,4,5,7,15
alta.convenios.users.104697=1,4,5,7,15
alta.convenios.users.102978=1,4,5,7,15
alta.convenios.users.109750=1,4,5,7,15
alta.convenios.users.105388=1,4,5,7,15
alta.convenios.users.106043=1,4,5,7,15
alta.convenios.users.102769=1,4,5,7,15
alta.convenios.users.102565=1,4,5,7,15
alta.convenios.users.100631=1,4,5,7,15
alta.convenios.users.100960=1,4,5,7,15
alta.convenios.users.108947=1,4,5,7,15
alta.convenios.users.102704=1,4,5,7,15
alta.convenios.users.105912=1,4,5,7,15
alta.convenios.users.100624=1,4,5,7,15
alta.convenios.users.101574=1,4,5,7,15
alta.convenios.users.104858=1,4,5,7,15
alta.convenios.users.109249=1,4,5,7,15
alta.convenios.users.103686=1,4,5,7,15
alta.convenios.users.102019=1,4,5,7,15
alta.convenios.users.103656=1,4,5,7,15
alta.convenios.users.110022=1,4,5,7,15
alta.convenios.users.104738=1,4,5,7,15
alta.convenios.users.106076=1,4,5,7,15
alta.convenios.users.106077=1,4,5,7,15
alta.convenios.users.102635=1,4,5,7,15
alta.convenios.users.100785=1,4,5,7,15
alta.convenios.users.100862=1,4,5,7,15
alta.convenios.users.105391=1,4,5,7,15
alta.convenios.users.101656=1,4,5,7,15
alta.convenios.users.105025=1,4,5,7,15
alta.convenios.users.105390=1,4,5,7,15
alta.convenios.users.105515=1,4,5,7,15
alta.convenios.users.109363=1,4,5,7,15
alta.convenios.users.103263=1,4,5,7,15
alta.convenios.users.106199=1,4,5,7,15
alta.convenios.users.101080=1,4,5,7,15
alta.convenios.users.110014=1,4,5,7,15
alta.convenios.users.111047=1,4,5,7,15
alta.convenios.users.102770=1,4,5,7,15
alta.convenios.users.103209=1,4,5,7,15
alta.convenios.users.109416=1,4,5,7,15
alta.convenios.users.103322=1,4,5,7,15
alta.convenios.users.102263=1,4,5,7,15
alta.convenios.users.102309=1,4,5,7,15
alta.convenios.users.104897=1,4,5,7,15
alta.convenios.users.106065=1,4,5,7,15
alta.convenios.users.104921=1,4,5,7,15
alta.convenios.users.101532=1,4,5,7,15
alta.convenios.users.104123=1,4,5,7,15
alta.convenios.users.102865=1,4,5,7,15
alta.convenios.users.103112=1,4,5,7,15
alta.convenios.users.106174=1,4,5,7,15
alta.convenios.users.109083=1,4,5,7,15
alta.convenios.users.102427=1,4,5,7,15
alta.convenios.users.104862=1,4,5,7,15
alta.convenios.users.100961=1,4,5,7,15
alta.convenios.users.102902=1,4,5,7,15
alta.convenios.users.103837=1,4,5,7,15
alta.convenios.users.105386=1,4,5,7,15
alta.convenios.users.111053=1,4,5,7,15
alta.convenios.users.110522=17
alta.convenios.users.106039=1,4,5,7,15
alta.convenios.users.109884=1,4,5,7,15
alta.convenios.users.112783=1,4,5,7,15
alta.convenios.users.113221=1,4,5,7,15

